import { Inter } from 'next/font/google'
import './globals.css'
import GlobalState from '@/Context'
import Navbar from '@/Components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'E-commerce',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalState>
          <Navbar/>
          <main className=' flex min-h-screen flex-col mt-[78px] bg-white'>{children}</main>
        </GlobalState>

  
      </body>
    </html>
  )
}
